services:
  postgres:
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10 -c max_connections=200 -c max_slot_wal_keep_size=2GB
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:13
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "/opt/keycloak/bin/kc.sh start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    ports:
      - "9094:8080"
    volumes:
      - './target/keycloak-theme-esil-1.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-theme-esil-1.0.0-SNAPSHOT.jar'
    depends_on:
      - postgres
    environment:
      KC_HOSTNAME: localhost
      # KC_HOSTNAME_STRICT: "false"
      # KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info

volumes:
  postgres_data:
    driver: local
